E2Helper.Descriptions["isPlayerInVR(e)"] = "Returns 1 or 0 for if ply is in VR. [VRCore]"
E2Helper.Descriptions["usingEmptyHandsVR(e)"] = "Returns 1 or 0 for if ply is using empty hands in VR. [VRCore]"
E2Helper.Descriptions["getHMDPosVR(e)"] = "Gives vector position of HMD/head of ply. [VRCore]"
E2Helper.Descriptions["getHMDAngVR(e)"] = "Gives angle of HMD/head of ply. [VRCore]"
E2Helper.Descriptions["getLeftHandPosVR(e)"] = "Returns vector position of left hand of ply in VR. [VRCore]"
E2Helper.Descriptions["getLeftHandAngVR(e)"] = "Returns angle of left hand of ply in VR. [VRCore]"
E2Helper.Descriptions["getRightHandPosVR(e)"] = "Returns vector position of right hand of ply in VR. [VRCore]"
E2Helper.Descriptions["getRightHandAngVR(n)"] = "Returns angle of right hand of ply in VR. [VRCore]"
